# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Build
      run: ./build/build.sh
    - name: Check
      run: |
        cd ./output
        ls -l D1_Basic*.zip
        ls -l D1_Extra*.zip
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: ./output
